### PR TITLE
Line 3 is changed

### PR DESCRIPTION
**Pull request by devasyarajguru**

### CODE REVIEW

**Comment by jehna** [comment]
Good job ✅ Keep it up!

**Comment by devasyarajguru** [comment]
I had generated Pull request  for practice . Can you merge  my PR?

**Comment by jehna** [comment]
No, unfortunately I cannot merge this as it would change the source repo. If you want to practice merges, you can create the pull request to your own fork at https://github.com/devasyarajguru/readme-best-practices/pulls

Then you can merge the pull request yourself!

**Comment by jehna** [comment]
Otherwise you're free to use this repo as a practice target :)

**Comment by devasyarajguru** [comment]
okay thank you

**Pull request closed without merging**
