### PR TITLE
docs(readme): move config section higher

### PR DESCRIPTION
**Pull request by schalkneethling**
I would recommend moving the configuration section higher as users might need that even before development or building.

### CODE REVIEW

**Comment by jehna** [comment]
"Configuration" has several sub-headings under it (e.g. "argument 1"), which in this pull request would change to be under the heading "Features", which does not make so much sense.

I'd add a new heading called e.g. "Initial configuration" under the "Getting started" paragraph. I this section you could state that some projects require initial configuration (e.g. access tokens or keys), and document where they must be used in order to start the project for the first time.

**Comment by schalkneethling** [comment]
@jehna That makes a lot of sense. I will update the PR to reflect your suggestion.

**Comment by jehna** [comment]
Thanks for the update @schalkneethling!

I changed the new section to be under "Getting started" section, if that's okay by you?

**Comment by schalkneethling** [comment]
Thanks @jehna

**Pull request merged**
